dotnet-outdated/dotnet-outdated

- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
For debugging purposes, I added the full error message. In some cases only info about msbuild version like:
```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```
This means that the actual error log seem to be hidden and thus making debugging somewhat more difficult.
> Added full error to exception

- test/DotNetOutdated.Tests/DotNetOutdated.Tests.csproj
System.IO.Abstractions.TestingHelpers brings in this dependency anyway. And this just causes Dependabot to trip up.
> Remove System.IO.Abstractions reference from test project

- src/DotNetOutdated.Core/Services/NuGetPackageResolutionService.cs
- test/DotNetOutdated.Tests/NuGetPackageResolutionServiceTests.cs
While working on some automation built on top of `DotNetOutdatedTool.Core` I found that when locking the minor version, updates between .NET 6.0 previews were not being detected.
For example, with a Major or Minor lock, `6.0.0-preview.2.21154.6` does not correctly detect the upgrade to `6.0.0-preview.3.21201.13`. It works without a lock, but that isn't _technically_ what I want, as if there was a preview of 6.1 or 7.0 available concurrently, I wouldn't want either of those as the latest for my use case.
I'm fairly sure the first part of the fix is correct using the `NuGetVersionFloatBehavior` values that are specific to prereleases, but I'm not so sure about the second part. While it fixes my test case, it doesn't _feel_ correct.
Looking at the [code for …
> Fix incorrect floating behaviour

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- src/DotNetOutdated/DotNetOutdated.csproj
- test/DotNetOutdated.Tests/DotNetOutdated.Tests.csproj
Adding .NET 6 support as (on my machine anyway) homebrew only leaves the latest SDK/runtime combo for .NET installed and so I was getting the following error when trying to run dotnet outdated
```text
▲ project [master] dotnet outdated -u:prompt
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
- The following frameworks were found:
6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=osx.11.0-x64
```
I followed the previous pull request #45 for when support for .NET 5 …
> Add .NET 6 support

- src/DotNetOutdated.Core/DotNetOutdated.Core.csproj
- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
- src/DotNetOutdated.Core/TempDirectory.cs
This is a just in case change and shouldn't be merged.
We make use of a deprecated call in the NuGet libraries. This is a temporary, hacky, workaround in case there is any urgency to update them to a version without that method available. i.e. critical security update
> Replace deprecated call to DependencyGraphSpec(JObject)

- src/DotNetOutdated/Formatters/JsonFormatter.cs
Fix `The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.`.
> Fix compiler warning

- .github/workflows/release.yml
The PR addresses the broken release workflow. This is due to `PackageOutputPath` working differently with relative paths and absolute ones
> Fix broken build

- README.md
- src/DotNetOutdated/Models/AnalyzedProject.cs
- src/DotNetOutdated/Program.cs
- test/DotNetOutdated.Tests/VersionNumberColoringTests.cs
Added support for a command line parameter --all to list all dependencies including the ones that do not need upgrades as detailed in #344
Example
```bash
dotnet-outdated.exe -t --all
» aspnettest
[net7.0]
Microsoft.AspNetCore.OpenApi                    7.0.8 == 7.0.8
Microsoft.Extensions.ApiDescription.Server [T]  6.0.5 -> 7.0.8
Microsoft.OpenApi [T]                           1.4.3 -> 1.6.5
Swashbuckle.AspNetCore                          6.4.0 -> 6.5.0
Swashbuckle.AspNetCore.Swagger [T]              6.4.0 -> 6.5.0
Swashbuckle.AspNetCore.SwaggerGen [T]           6.4.0 -> 6.5.0
Swashbuckle.AspNetCore.SwaggerUI [T]            6.4.0 -> 6.5.0
Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. …
```
> #344 Added parameter --all to list all dependencies including the ones that do not need upgrades

- test/DotNetOutdated.Tests/DependencyGraphServiceTests.cs
Use `Assert.Empty()` instead of checking the count is equal to 0.
> Fix xunit analyzer warning

- test/DotNetOutdated.Tests/NuGetPackageResolutionServiceTests.cs
Fix xUnit1030 warning by removing call to `ConfigureAwait(false)`.
> Fix xUnit1030 warning

- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
Previous behavior: The update of outdated packages might break because of downgrade warnings.
An upgrade might actually fix downgrade warnings so the warning NU1605 is now ignored during graph build which makes the tool more reliable.
> Ignoring  downgrade warning NU1605 during preparation (graph build)

- src/DotNetOutdated.Core/Services/INuGetPackageResolutionService.cs
- src/DotNetOutdated.Core/Services/NuGetPackageResolutionService.cs
- src/DotNetOutdated/Program.cs
- test/DotNetOutdated.Tests/NuGetPackageResolutionServiceTests.cs
Support allowing for a variable number of parts for a release label prefix to support the scenario of not moving between .NET preview releases.
The motivation here is that if I'm testing prerelease versions of the next preview of .NET 8, I want the NuGet packages updates to remain within the same preview version and not pick up packages from the preview after that.
For instance, with the current behaviour I get this output:
```
> dotnet outdated --no-restore --version-lock Minor --include Microsoft.AspNetCore.
» Project
[net8.0]
Microsoft.AspNetCore.Authentication.JwtBearer   8.0.0-rc.1.23416.4 -> 8.0.0-rc.2.23417.18
Microsoft.AspNetCore.DataProtection.Extensions  8.0.0-rc.1.23416.4 -> 8.0.0-rc.2.23417.18
» Project.Tests
[net8.0]
Microsoft.AspNetCore.Mvc.Testing  8.0.0-rc.1.23416.4 -> …
```
> Support variable release prefix lengths

- src/DotNetOutdated.Core/Services/DotNetPackageService.cs
- src/DotNetOutdated.Core/Services/IDotNetPackageService.cs
- src/DotNetOutdated/Program.cs
Support older project file formats by removing the package before updating so duplicate references are not included.
The reason for this PR is that with legacy style csproj files, the `dotnet add` command will add a duplicate package reference instead of incrementing the version number. This is a [known issue](https://github.com/NuGet/Home/issues/8561) with NuGet and is not going to be resolved. 
In order to continue using the tool to update packages in legacy projects, the workaround is to remove the package before updating the version. I have tested this change and am currently using a built-from-source version with this fix included so I can update legacy projects. 
This PR is a more robust version of #242 with better project style detection and based off the most recent code changes. …
> Add better support for legacy project formats

- src/DotNetOutdated.Core/Services/CentralPackageVersionManagementService.cs
- test/DotNetOutdated.Tests/CentralPackageVersionManagementTests.cs
- test/DotNetOutdated.Tests/TestData/CPVMFile.props
resolve https://github.com/dotnet-outdated/dotnet-outdated/issues/518, make `dotnet-outdated` support updating nuget versions in `<GlobalPackageReferences>` in `Directory.Packages.props`.
> Support updating GlobalPackageReference

- .github/workflows/release.yml
- .github/workflows/test.yml
Bump actions to latest versions to resolve [Node.js v16 deprecation warnings](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
> Bump actions

- .github/workflows/test.yml
- src/DotNetOutdated/Program.cs
- src/DotNetOutdated/ProjectExtensions.cs
- test/DotNetOutdated.Tests/DotNetOutdated.Tests.csproj
- test/DotNetOutdated.Tests/ProjectExtensionsTests.cs
Fix XML query incorrectly identifying a project file as a non-SDK style project if it contains an `xmlns` attribute.
I discovered this through https://github.com/martincostello/dotnet-bumper/pull/228 where I switched to using the MSBuildProjectCreator library to create test projects, which are always emitted with the MSBuild namespace. After doing this, the some of the tests would fail due to dotnet outdated failing to update packages correctly as it was misidentifying the projects as non-SDK projects:
```console
Project format not SDK style, removing package before upgrade.
```
For now, I've worked around this by manually removing the `xmlns` value from the projects the tests create: https://github.com/martincostello/dotnet-bumper/pull/228/commits/42468393cab4cf36c71e3d71c5fea03593d499ec …
> Fix XML query for Project SDK

- .github/workflows/test.yml
- src/DotNetOutdated.Core/DotNetOutdated.Core.csproj
- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
- test-projects/build-props/Directory.Build.props
- test/DotNetOutdated.Tests/DependencyGraphServiceTests.cs
- test/DotNetOutdated.Tests/DotNetOutdated.Tests.csproj
- test/DotNetOutdated.Tests/EndToEndTests.cs
- Disable NuGet package auditing when restoring packages.
- Enable C# 12 in DotNetOutdated.Core.
- Tidy-up unused code in `DependencyGraphServiceTests`.
- Add end-to-end tests using the existing test projects.
Resolves #548.
> Fix failure if existing packages have vulnerabilities

- .gitattributes
- src/DotNetOutdated/Formatters/CsvFormatter.cs
- src/DotNetOutdated/Formatters/JsonFormatter.cs
- src/DotNetOutdated/Formatters/MarkdownFormatter.cs
- src/DotNetOutdated/IOutputFormatter.cs
- src/DotNetOutdated/Models/AnalyzedProject.cs
- src/DotNetOutdated/Program.cs
- test/DotNetOutdated.Tests/EndToEndTests.cs
- test/DotNetOutdated.Tests/JsonFormatterTests.cs
This should help with performance. Also one remaining Newtonsoft reference was replaced with System.Text.Json
The `await using (something.ConfigureAwait(false))` pattern will help allow IAsyncDisposable to be used in conjunction with CA2007. See [this thread](https://stackoverflow.com/questions/69905541/getting-ca2007-after-upgrading-to-6-0-version-of-the-roslyn-analyzers) for details.
Needed to add a .gitattributes file so that this could produce a good diff. Otherwise, all the line endings are screwed up
> Async Formatters for performance

- test/DotNetOutdated.Tests/EndToEndTests.cs
Actually use the temporary directory.
> Fix end-to-end tests

- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
- src/DotNetOutdated.Core/Services/IDependencyGraphService.cs
- src/DotNetOutdated.Core/Services/IProjectAnalysisService.cs
- src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs
- src/DotNetOutdated/Program.cs
- test-projects/development-dependencies-lock/development-dependencies-lock.csproj
- test-projects/development-dependencies-lock/packages.lock.json
- test/DotNetOutdated.Tests/DependencyGraphServiceTests.cs
- test/DotNetOutdated.Tests/EndToEndTests.cs
This PR adds support for specifying the runtime during the dependency graph building process. In our project, we use this .NET tool within our CI/CD pipelines and encountered issues when projects failed due to the presence of a package.lock.json file and the csproj property <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>.
We need to build and publish our solution for a specific runtime. To achieve this, we use the command `dotnet restore --force-evaluate --runtime win-x64 && dotnet build && dotnet publish --runtime win-x64` However, the tool currently fails to generate the dependency graph because it cannot detect the specified runtime for restoring packages. This PR addresses this issue by ensuring the runtime is correctly identified and handled during the restore …
> Add runtime for msbuild dependency graph 

- .github/workflows/release.yml
- .github/workflows/test.yml
- src/DotNetOutdated.Core/DotNetOutdated.Core.csproj
- src/DotNetOutdated/DotNetOutdated.csproj
- test/DotNetOutdated.Tests/DotNetOutdated.Tests.csproj
- test/DotNetOutdated.Tests/EndToEndTests.cs
These are the current LTS and STS respectively and should be the targeted frameworks
closes #612
> chore: update TargetFrameworks to net8 and net9

- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
- src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs
This PR fixes incorrect async behavior as per [MSDN](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming).
> Fix incorrect `async` usage

- src/DotNetOutdated/Program.cs
Updating currently fails for projects using the old project style with central package management, due to an oversight in #538.
Projects using the old project style need to remove the package before updating (due to a long standing NuGet bug), but this is not necessary or possible when using CPM.
This PR adds a check to avoid attempting to remove the reference if the package is centrally managed.
> Fix updating legacy projects using CPM

- src/DotNetOutdated.Core/Services/DependencyGraphService.cs
- src/DotNetOutdated.Core/Services/DotNetPackageService.cs
- src/DotNetOutdated.Core/Services/DotNetRestoreService.cs
- src/DotNetOutdated.Core/Services/DotNetRunner.cs
- src/DotNetOutdated/DotNetOutdated.csproj
- src/DotNetOutdated/Program.cs
- test/DotNetOutdated.Tests/DependencyGraphServiceTests.cs
While working on #640 I spotted a few things that could be improved:
- Use `ProcessStartInfo.ArgumentList` to start `dotnet` to avoid needing to quote/concatenate arguments into a single string.
- Use `Parallel.ForEachAsync()` instead of manually managing tasks.
- Remove duplicate MSBuild property.
Also applies some IDE code refactoring suggestions in touched files such as using collection expressions and using primary constructors.
> Use ProcessStartInfo.ArgumentList and Parallel.ForEachAsync

- src/DotNetOutdated.Core/Services/INuGetPackageInfoServiceLogger.cs
- src/DotNetOutdated.Core/Services/NuGetPackageInfoService.cs
- src/DotNetOutdated/NuGetPackageInfoServiceLogger.cs
- src/DotNetOutdated/Program.cs
This is a fix for issue [Issue-576](https://github.com/dotnet-outdated/dotnet-outdated/issues/576)
It will use package source mapping in the same NuGet config file as NuGet package source.
> [Issue-576]use package source mapping in command

- src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs
When transitive dependencies have alternate casing used in their definitions, then these dependencies are resolved incorrectly. Version range of the dependency is not discovered and execution fails with error message: `"Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?"` (because `UpgradeServerity` of the package is `Unknown`).
For example package [FluentValidation.DependencyInjectionExtensions](https://www.nuget.org/packages/FluentValidation.DependencyInjectionExtensions/12.0.0#dependencies-body-tab) which has dependency on package *Microsoft.Extensions.Dependencyinjection.Abstractions* (pay attention to lowercase "i" at the start of "injection").
Fixed by using case-insensitive comparing of package …
> Fix version detection of transitive dependencies
